import type { VisualDecisionPacket } from '../../../packages/project-contracts/src/index.ts';

export function structuredAnalysisPacketFixture(): VisualDecisionPacket {
  return {
    schemaVersion: '1.0',
    projectId: 'project-generic',
    projectFacts: {
      brandName: {
        value: 'Example Brand',
        source: 'project_record',
        evidenceRefs: ['project:brand-name'],
        confidence: 1,
        status: 'confirmed',
      },
      industry: {
        value: 'Hospitality',
        source: 'source_document',
        evidenceRefs: ['document:industry'],
        confidence: 0.9,
        status: 'confirmed',
      },
      brandRole: {
        value: 'A welcoming service destination',
        source: 'source_document',
        evidenceRefs: ['document:brand-role'],
        confidence: 0.9,
        status: 'confirmed',
      },
    },
    lockedAssets: [{
      assetId: 'logo-1',
      type: 'logo',
      value: 'Confirmed logo',
      lockSource: 'user_confirmed',
      evidenceRefs: ['asset:logo-1'],
    }],
    assetInventory: {
      logoAssets: [],
      colorAssets: [],
      typographyAssets: [],
      graphicMotifs: [],
      imageryAssets: [],
      layoutPatterns: [],
      materialCues: [],
      packagingStructures: [],
      spatialCues: [],
      copyAssets: [],
    },
    diagnosis: {
      valuableAssets: [{
        target: 'confirmed identity',
        observation: 'The source contains a repeatable open-frame motif',
        whyItMatters: 'It can preserve recognition across media',
        evidenceRefs: ['asset:motif-1'],
        confidence: 0.9,
      }],
      overusedExpressions: [],
      outdatedExpressions: [],
      weakSystemAreas: [],
      categoryCliches: [],
      brandMisreadRisks: [{
        code: 'risk-generic',
        target: 'generic service venue',
        description: 'May be mistaken for a generic service venue',
        observation: 'Current hierarchy is not distinctive',
        whyItMatters: 'The brand role is unclear',
        appliesTo: { taskFamilies: ['space', 'packaging'] },
        evidenceRefs: ['diagnosis:risk-1'],
        confidence: 0.85,
        status: 'probable',
      }],
      crossMediaGaps: [],
    },
    creativeDecision: {
      brandRoleStatement: 'Make the service promise visible at every touchpoint',
      upgradeFrom: ['generic and fragmented'],
      preserveCore: ['confirmed identity'],
      upgradeTo: ['clear and welcoming'],
      uniqueUpgradeThesis: 'Turn service clarity into a spatial and material system',
      targetWorldview: ['clear', 'welcoming'],
      toneBoundaries: [
        { target: 'confident', avoid: ['institutional'] },
        { target: 'warm', avoid: ['decorative nostalgia'] },
      ],
      strategicNegatives: ['generic decoration'],
    },
    abstractions: [{
      sourceAsset: 'asset:motif-1',
      semanticMeaning: ['welcome'],
      formalProperties: ['open frame'],
      rhythmProperties: ['measured repetition'],
      materialPotential: ['translucent partition'],
      lightingPotential: ['soft edge light'],
      forbiddenLiteralUse: ['literal icon wall'],
      evidenceRefs: ['asset:motif-1'],
      confidence: 0.85,
    }],
    mediaTranslations: {
      sharedBrandCore: ['clear service promise'],
      spatial: {
        status: 'ready',
        spatialConcept: 'A clear sequence of service zones',
        brandRoleManifestation: ['Visible service steps'],
        signatureSpatialMechanism: ['Layered open frames guide movement'],
        functionalNetwork: ['arrival to consultation to completion'],
        positiveDifferentiators: ['Service logic is visible'],
        mustBeVisible: ['arrival point', 'service point'],
        structureLanguage: ['open frame'],
        materialLanguage: [{
          material: 'matte metal',
          behavior: ['precise edge'],
          brandRole: 'makes service order legible',
          forbidden: ['mirror finish'],
        }],
        lightingLanguage: {
          source: ['soft area light'],
          contrast: 'low contrast',
          interactionWithMaterials: ['soft reflection'],
          forbidden: ['colored effect light'],
        },
        colorBehavior: {
          primary: [{ name: 'warm white', role: 'clear base' }],
          secondary: [{ name: 'natural wood', role: 'human warmth' }],
          accent: [{ name: 'identity black', role: 'precise identity emphasis' }],
          forbidden: ['neon gradient'],
        },
        brandIntegration: ['identity at arrival'],
        functionalRelationships: ['guest sees service point from arrival'],
        sceneProgram: ['arrival', 'service', 'consultation'],
        peopleBehavior: ['staff guides guest'],
        functionalExperience: [],
        sceneMisreadRisks: [],
      },
      packaging: {
        status: 'ready',
        packagingConcept: 'A clear opening sequence',
        productAndCategoryRole: ['confirmed service kit'],
        structureStrategy: [{
          structure: 'confirmed folding carton',
          purpose: 'protect the documented kit',
          locked: true,
          evidenceRefs: ['source:packaging-structure'],
        }],
        openingExperience: ['open in one clear step'],
        productArrangement: ['documented kit remains fixed'],
        graphicTranslation: [],
        informationHierarchy: ['brand', 'product'],
        substrateLanguage: ['uncoated paper'],
        craftLanguage: [{
          craft: 'deboss',
          purpose: 'identity emphasis',
          forbiddenUse: ['full-surface texture'],
        }],
        colorBehavior: {
          base: ['warm white'],
          identity: ['black'],
          accent: [],
          forbidden: ['neon gradient'],
        },
        logoPolicy: ['use confirmed logo only'],
        seriesArchitecture: [],
        photographyDirection: ['clear product view'],
        packagingMisreadRisks: [],
        missingRequiredFields: [],
      },
      poster: {
        status: 'interface_only',
        concept: '',
        expressionLanguage: [],
        misreadRisks: [],
      },
      vi: {
        status: 'interface_only',
        concept: '',
        expressionLanguage: [],
        misreadRisks: [],
      },
    },
    colorSystem: {
      primary: [{ name: 'warm white', role: 'clear base' }],
      secondary: [{ name: 'natural wood', role: 'human warmth' }],
      accent: [{ name: 'identity black', role: 'precise identity emphasis' }],
      forbidden: ['neon gradient'],
    },
    materialSystem: [{
      material: 'matte metal',
      behavior: ['precise edge'],
      brandRole: 'makes service order legible',
      forbidden: ['mirror finish'],
    }],
    lightingSystem: {
      source: ['soft area light'],
      contrast: 'low contrast',
      interactionWithMaterials: ['soft reflection'],
      forbidden: ['colored effect light'],
    },
    provenance: {
      createdFrom: ['project:generic', 'asset:motif-1'],
      generatedAt: '2026-01-01T00:00:00.000Z',
      modelId: 'test-model',
      sourceFingerprint: 'fingerprint-generic',
    },
    validation: {
      hardFactStatus: 'pass',
      mode: 'formal_upgrade',
      missingRequiredFacts: [],
      conflicts: [],
      executionDataStatus: 'ready',
      missingExecutionFields: [],
    },
  };
}
