/**
 * Visual Canon diagnostic constants.
 */

import type { CanonDiagnosticCode } from './contracts.ts';

export const CANON_DIAGNOSTIC_CODES: readonly CanonDiagnosticCode[] = [
  'CANON_SELECTION_REQUIRED',
  'CANON_SELECTION_INVALIDATED',
  'CANON_DIRECTION_NOT_FOUND',
  'CANON_DIRECTION_BLOCKED',
  'CANON_DIRECTION_STALE',
  'CANON_TRACE_INCOMPLETE',
  'CANON_RULE_UNGROUNDED',
  'CANON_LOCKED_ASSET_VIOLATION',
  'CANON_PROMPT_LEAKAGE',
  'CANON_PRODUCTION_SPEC_LEAKAGE',
  'CANON_DRIFT_NEW_MECHANISM',
  'CANON_DRIFT_NEW_FAMILY',
  'CANON_DRIFT_NEW_BRAND',
  'CANON_DRIFT_LOCKED_BEHAVIOR',
] as const;
